### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'data'

### ISSUE THREAD

**Issue by doctormachine** [lassonet/lassonet#1]
Hi,
I am trying to execute the $CUDA_VISIBLE_DEVICES=0,1 python d1/train_c.py --config d1/config/s0_np2048_pn.yaml. However, I am getting the following error:
Traceback (most recent call last):
  File "d1/train_c.py", line 193, in <module>
    train()
  File "d1/train_c.py", line 80, in train
    train_dataset = tf.data.Dataset \
AttributeError: module 'tensorflow' has no attribute 'data'

**Comment by doctormachine** [comment]
I have changed the tf.data.Dataset to tf.contrib.data.Dataset. However, I am getting a new error:

Traceback (most recent call last):
  File "d1/train_c.py", line 193, in <module>
    train()
  File "d1/train_c.py", line 82, in train
    .batch(cfg.BATCH_SIZE) \
AttributeError: 'BatchDataset' object has no attribute 'prefetch'

**Comment by chenzhutian** [comment]
Hi, could you please provide the version of your tensorflow, python, os?
It seems that you use a wrong version of TF

**Comment by doctormachine** [comment]
Hi,
I have tried TF1.12.0. However, it doesn't work for me.  It was showing following error:
tensorflow.python.framework.errors_impl.NotFoundError: /home/mdmursalin/lassonet2/lassonet/tf_ops/sampling/tf_sampling_so.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

I have tried different versions. Currently, the version I am working:
python=3.6.10
tensorflow-gpu=1.2.1
os=Ubuntu 18.04

One more thing I want to mention is: in the tf_ops/3d_interpolation I haven't found the file named
tf_interpolate.cu.o

Thank you so much. I look forward to hearing from you.

**Comment by chenzhutian** [comment]
Have you compiled the tf_ops?
check `tf_xxx_compile.sh` under each ops subfolder
Please change the paths in the .sh file accordingly

**Comment by doctormachine** [comment]
I have compiled the .sh files. However, the .sh file in the tf_ops/3d_interpolation requires  tf_interpolate.cu.o file, which is not present in the directory. Could you please share that file? 
Also, can you share your complete  tf_ops folder? 

I am wondering if you clone the repository and install a new virtual environment according to the installation guide for a quick check. Thank you so much. I look forward to hearing from you.

**Comment by chenzhutian** [comment]
`tf_interpolate.cu.o` should be a compiled output rather than a pre-provided file.

Please check this line https://github.com/lassonet/lassonet/blob/master/tf_ops/3d_interpolation/tf_interpolate_compile.sh#L2

`/usr/local/cuda-9.0/bin/nvcc tf_interpolate.cu -o tf_interpolate.cu.o` means compile `tf_interpolate.cu` and output `tf_interpolate.cu.o`

Thus it seems that you does not succesfully compile the tf_ops.
Any msg during the compilation?

BTW, I will clone and have a check.

**Comment by doctormachine** [comment]
Thank you chenzhutian. I will try and let you know if there is any issue.
